/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PersonalDataConsentRouteImport } from './routes/personal-data-consent'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as OfferRouteImport } from './routes/offer'
import { Route as NewsRouteImport } from './routes/news'
import { Route as MineRouteImport } from './routes/mine'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JoinRouteImport } from './routes/join'
import { Route as CabinetRouteImport } from './routes/cabinet'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UNicknameRouteImport } from './routes/u.$nickname'
import { Route as PaymentSuccessRouteImport } from './routes/payment.success'
import { Route as PaymentPendingRouteImport } from './routes/payment.pending'
import { Route as PaymentFailedRouteImport } from './routes/payment.failed'
import { Route as NewsSlugRouteImport } from './routes/news.$slug'
import { Route as CabinetStatsRouteImport } from './routes/cabinet.stats'
import { Route as CabinetNewsRouteImport } from './routes/cabinet.news'
import { Route as CabinetBankRouteImport } from './routes/cabinet.bank'
import { Route as CabinetAdminRouteImport } from './routes/cabinet.admin'
import { Route as CabinetNewsSlugRouteImport } from './routes/cabinet.news.$slug'
import { Route as CabinetBankTransferRouteImport } from './routes/cabinet.bank.transfer'
import { Route as CabinetBankHistoryRouteImport } from './routes/cabinet.bank.history'
import { Route as CabinetBankCardsRouteImport } from './routes/cabinet.bank.cards'
import { Route as CabinetAdminWhitelistRouteImport } from './routes/cabinet.admin.whitelist'
import { Route as CabinetAdminUsersRouteImport } from './routes/cabinet.admin.users'
import { Route as CabinetAdminPromosRouteImport } from './routes/cabinet.admin.promos'
import { Route as CabinetAdminPostsRouteImport } from './routes/cabinet.admin.posts'
import { Route as CabinetAdminPaymentsRouteImport } from './routes/cabinet.admin.payments'
import { Route as CabinetAdminOverviewRouteImport } from './routes/cabinet.admin.overview'
import { Route as CabinetAdminNavigationRouteImport } from './routes/cabinet.admin.navigation'
import { Route as CabinetAdminApplicationsRouteImport } from './routes/cabinet.admin.applications'

const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalDataConsentRoute = PersonalDataConsentRouteImport.update({
  id: '/personal-data-consent',
  path: '/personal-data-consent',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const OfferRoute = OfferRouteImport.update({
  id: '/offer',
  path: '/offer',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const MineRoute = MineRouteImport.update({
  id: '/mine',
  path: '/mine',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const CabinetRoute = CabinetRouteImport.update({
  id: '/cabinet',
  path: '/cabinet',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UNicknameRoute = UNicknameRouteImport.update({
  id: '/u/$nickname',
  path: '/u/$nickname',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => PaymentRoute,
} as any)
const PaymentPendingRoute = PaymentPendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => PaymentRoute,
} as any)
const PaymentFailedRoute = PaymentFailedRouteImport.update({
  id: '/failed',
  path: '/failed',
  getParentRoute: () => PaymentRoute,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => NewsRoute,
} as any)
const CabinetStatsRoute = CabinetStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => CabinetRoute,
} as any)
const CabinetNewsRoute = CabinetNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => CabinetRoute,
} as any)
const CabinetBankRoute = CabinetBankRouteImport.update({
  id: '/bank',
  path: '/bank',
  getParentRoute: () => CabinetRoute,
} as any)
const CabinetAdminRoute = CabinetAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => CabinetRoute,
} as any)
const CabinetNewsSlugRoute = CabinetNewsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CabinetNewsRoute,
} as any)
const CabinetBankTransferRoute = CabinetBankTransferRouteImport.update({
  id: '/transfer',
  path: '/transfer',
  getParentRoute: () => CabinetBankRoute,
} as any)
const CabinetBankHistoryRoute = CabinetBankHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => CabinetBankRoute,
} as any)
const CabinetBankCardsRoute = CabinetBankCardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => CabinetBankRoute,
} as any)
const CabinetAdminWhitelistRoute = CabinetAdminWhitelistRouteImport.update({
  id: '/whitelist',
  path: '/whitelist',
  getParentRoute: () => CabinetAdminRoute,
} as any)
const CabinetAdminUsersRoute = CabinetAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => CabinetAdminRoute,
} as any)
const CabinetAdminPromosRoute = CabinetAdminPromosRouteImport.update({
  id: '/promos',
  path: '/promos',
  getParentRoute: () => CabinetAdminRoute,
} as any)
const CabinetAdminPostsRoute = CabinetAdminPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => CabinetAdminRoute,
} as any)
const CabinetAdminPaymentsRoute = CabinetAdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => CabinetAdminRoute,
} as any)
const CabinetAdminOverviewRoute = CabinetAdminOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => CabinetAdminRoute,
} as any)
const CabinetAdminNavigationRoute = CabinetAdminNavigationRouteImport.update({
  id: '/navigation',
  path: '/navigation',
  getParentRoute: () => CabinetAdminRoute,
} as any)
const CabinetAdminApplicationsRoute =
  CabinetAdminApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => CabinetAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/cabinet': typeof CabinetRouteWithChildren
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/mine': typeof MineRoute
  '/news': typeof NewsRouteWithChildren
  '/offer': typeof OfferRoute
  '/payment': typeof PaymentRouteWithChildren
  '/personal-data-consent': typeof PersonalDataConsentRoute
  '/privacy': typeof PrivacyRoute
  '/rules': typeof RulesRoute
  '/stats': typeof StatsRoute
  '/cabinet/admin': typeof CabinetAdminRouteWithChildren
  '/cabinet/bank': typeof CabinetBankRouteWithChildren
  '/cabinet/news': typeof CabinetNewsRouteWithChildren
  '/cabinet/stats': typeof CabinetStatsRoute
  '/news/$slug': typeof NewsSlugRoute
  '/payment/failed': typeof PaymentFailedRoute
  '/payment/pending': typeof PaymentPendingRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/u/$nickname': typeof UNicknameRoute
  '/cabinet/admin/applications': typeof CabinetAdminApplicationsRoute
  '/cabinet/admin/navigation': typeof CabinetAdminNavigationRoute
  '/cabinet/admin/overview': typeof CabinetAdminOverviewRoute
  '/cabinet/admin/payments': typeof CabinetAdminPaymentsRoute
  '/cabinet/admin/posts': typeof CabinetAdminPostsRoute
  '/cabinet/admin/promos': typeof CabinetAdminPromosRoute
  '/cabinet/admin/users': typeof CabinetAdminUsersRoute
  '/cabinet/admin/whitelist': typeof CabinetAdminWhitelistRoute
  '/cabinet/bank/cards': typeof CabinetBankCardsRoute
  '/cabinet/bank/history': typeof CabinetBankHistoryRoute
  '/cabinet/bank/transfer': typeof CabinetBankTransferRoute
  '/cabinet/news/$slug': typeof CabinetNewsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/cabinet': typeof CabinetRouteWithChildren
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/mine': typeof MineRoute
  '/news': typeof NewsRouteWithChildren
  '/offer': typeof OfferRoute
  '/payment': typeof PaymentRouteWithChildren
  '/personal-data-consent': typeof PersonalDataConsentRoute
  '/privacy': typeof PrivacyRoute
  '/rules': typeof RulesRoute
  '/stats': typeof StatsRoute
  '/cabinet/admin': typeof CabinetAdminRouteWithChildren
  '/cabinet/bank': typeof CabinetBankRouteWithChildren
  '/cabinet/news': typeof CabinetNewsRouteWithChildren
  '/cabinet/stats': typeof CabinetStatsRoute
  '/news/$slug': typeof NewsSlugRoute
  '/payment/failed': typeof PaymentFailedRoute
  '/payment/pending': typeof PaymentPendingRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/u/$nickname': typeof UNicknameRoute
  '/cabinet/admin/applications': typeof CabinetAdminApplicationsRoute
  '/cabinet/admin/navigation': typeof CabinetAdminNavigationRoute
  '/cabinet/admin/overview': typeof CabinetAdminOverviewRoute
  '/cabinet/admin/payments': typeof CabinetAdminPaymentsRoute
  '/cabinet/admin/posts': typeof CabinetAdminPostsRoute
  '/cabinet/admin/promos': typeof CabinetAdminPromosRoute
  '/cabinet/admin/users': typeof CabinetAdminUsersRoute
  '/cabinet/admin/whitelist': typeof CabinetAdminWhitelistRoute
  '/cabinet/bank/cards': typeof CabinetBankCardsRoute
  '/cabinet/bank/history': typeof CabinetBankHistoryRoute
  '/cabinet/bank/transfer': typeof CabinetBankTransferRoute
  '/cabinet/news/$slug': typeof CabinetNewsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/cabinet': typeof CabinetRouteWithChildren
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/mine': typeof MineRoute
  '/news': typeof NewsRouteWithChildren
  '/offer': typeof OfferRoute
  '/payment': typeof PaymentRouteWithChildren
  '/personal-data-consent': typeof PersonalDataConsentRoute
  '/privacy': typeof PrivacyRoute
  '/rules': typeof RulesRoute
  '/stats': typeof StatsRoute
  '/cabinet/admin': typeof CabinetAdminRouteWithChildren
  '/cabinet/bank': typeof CabinetBankRouteWithChildren
  '/cabinet/news': typeof CabinetNewsRouteWithChildren
  '/cabinet/stats': typeof CabinetStatsRoute
  '/news/$slug': typeof NewsSlugRoute
  '/payment/failed': typeof PaymentFailedRoute
  '/payment/pending': typeof PaymentPendingRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/u/$nickname': typeof UNicknameRoute
  '/cabinet/admin/applications': typeof CabinetAdminApplicationsRoute
  '/cabinet/admin/navigation': typeof CabinetAdminNavigationRoute
  '/cabinet/admin/overview': typeof CabinetAdminOverviewRoute
  '/cabinet/admin/payments': typeof CabinetAdminPaymentsRoute
  '/cabinet/admin/posts': typeof CabinetAdminPostsRoute
  '/cabinet/admin/promos': typeof CabinetAdminPromosRoute
  '/cabinet/admin/users': typeof CabinetAdminUsersRoute
  '/cabinet/admin/whitelist': typeof CabinetAdminWhitelistRoute
  '/cabinet/bank/cards': typeof CabinetBankCardsRoute
  '/cabinet/bank/history': typeof CabinetBankHistoryRoute
  '/cabinet/bank/transfer': typeof CabinetBankTransferRoute
  '/cabinet/news/$slug': typeof CabinetNewsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/cabinet'
    | '/join'
    | '/login'
    | '/mine'
    | '/news'
    | '/offer'
    | '/payment'
    | '/personal-data-consent'
    | '/privacy'
    | '/rules'
    | '/stats'
    | '/cabinet/admin'
    | '/cabinet/bank'
    | '/cabinet/news'
    | '/cabinet/stats'
    | '/news/$slug'
    | '/payment/failed'
    | '/payment/pending'
    | '/payment/success'
    | '/u/$nickname'
    | '/cabinet/admin/applications'
    | '/cabinet/admin/navigation'
    | '/cabinet/admin/overview'
    | '/cabinet/admin/payments'
    | '/cabinet/admin/posts'
    | '/cabinet/admin/promos'
    | '/cabinet/admin/users'
    | '/cabinet/admin/whitelist'
    | '/cabinet/bank/cards'
    | '/cabinet/bank/history'
    | '/cabinet/bank/transfer'
    | '/cabinet/news/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/cabinet'
    | '/join'
    | '/login'
    | '/mine'
    | '/news'
    | '/offer'
    | '/payment'
    | '/personal-data-consent'
    | '/privacy'
    | '/rules'
    | '/stats'
    | '/cabinet/admin'
    | '/cabinet/bank'
    | '/cabinet/news'
    | '/cabinet/stats'
    | '/news/$slug'
    | '/payment/failed'
    | '/payment/pending'
    | '/payment/success'
    | '/u/$nickname'
    | '/cabinet/admin/applications'
    | '/cabinet/admin/navigation'
    | '/cabinet/admin/overview'
    | '/cabinet/admin/payments'
    | '/cabinet/admin/posts'
    | '/cabinet/admin/promos'
    | '/cabinet/admin/users'
    | '/cabinet/admin/whitelist'
    | '/cabinet/bank/cards'
    | '/cabinet/bank/history'
    | '/cabinet/bank/transfer'
    | '/cabinet/news/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/cabinet'
    | '/join'
    | '/login'
    | '/mine'
    | '/news'
    | '/offer'
    | '/payment'
    | '/personal-data-consent'
    | '/privacy'
    | '/rules'
    | '/stats'
    | '/cabinet/admin'
    | '/cabinet/bank'
    | '/cabinet/news'
    | '/cabinet/stats'
    | '/news/$slug'
    | '/payment/failed'
    | '/payment/pending'
    | '/payment/success'
    | '/u/$nickname'
    | '/cabinet/admin/applications'
    | '/cabinet/admin/navigation'
    | '/cabinet/admin/overview'
    | '/cabinet/admin/payments'
    | '/cabinet/admin/posts'
    | '/cabinet/admin/promos'
    | '/cabinet/admin/users'
    | '/cabinet/admin/whitelist'
    | '/cabinet/bank/cards'
    | '/cabinet/bank/history'
    | '/cabinet/bank/transfer'
    | '/cabinet/news/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  CabinetRoute: typeof CabinetRouteWithChildren
  JoinRoute: typeof JoinRoute
  LoginRoute: typeof LoginRoute
  MineRoute: typeof MineRoute
  NewsRoute: typeof NewsRouteWithChildren
  OfferRoute: typeof OfferRoute
  PaymentRoute: typeof PaymentRouteWithChildren
  PersonalDataConsentRoute: typeof PersonalDataConsentRoute
  PrivacyRoute: typeof PrivacyRoute
  RulesRoute: typeof RulesRoute
  StatsRoute: typeof StatsRoute
  UNicknameRoute: typeof UNicknameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personal-data-consent': {
      id: '/personal-data-consent'
      path: '/personal-data-consent'
      fullPath: '/personal-data-consent'
      preLoaderRoute: typeof PersonalDataConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offer': {
      id: '/offer'
      path: '/offer'
      fullPath: '/offer'
      preLoaderRoute: typeof OfferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mine': {
      id: '/mine'
      path: '/mine'
      fullPath: '/mine'
      preLoaderRoute: typeof MineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cabinet': {
      id: '/cabinet'
      path: '/cabinet'
      fullPath: '/cabinet'
      preLoaderRoute: typeof CabinetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$nickname': {
      id: '/u/$nickname'
      path: '/u/$nickname'
      fullPath: '/u/$nickname'
      preLoaderRoute: typeof UNicknameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/success': {
      id: '/payment/success'
      path: '/success'
      fullPath: '/payment/success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof PaymentRoute
    }
    '/payment/pending': {
      id: '/payment/pending'
      path: '/pending'
      fullPath: '/payment/pending'
      preLoaderRoute: typeof PaymentPendingRouteImport
      parentRoute: typeof PaymentRoute
    }
    '/payment/failed': {
      id: '/payment/failed'
      path: '/failed'
      fullPath: '/payment/failed'
      preLoaderRoute: typeof PaymentFailedRouteImport
      parentRoute: typeof PaymentRoute
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof NewsRoute
    }
    '/cabinet/stats': {
      id: '/cabinet/stats'
      path: '/stats'
      fullPath: '/cabinet/stats'
      preLoaderRoute: typeof CabinetStatsRouteImport
      parentRoute: typeof CabinetRoute
    }
    '/cabinet/news': {
      id: '/cabinet/news'
      path: '/news'
      fullPath: '/cabinet/news'
      preLoaderRoute: typeof CabinetNewsRouteImport
      parentRoute: typeof CabinetRoute
    }
    '/cabinet/bank': {
      id: '/cabinet/bank'
      path: '/bank'
      fullPath: '/cabinet/bank'
      preLoaderRoute: typeof CabinetBankRouteImport
      parentRoute: typeof CabinetRoute
    }
    '/cabinet/admin': {
      id: '/cabinet/admin'
      path: '/admin'
      fullPath: '/cabinet/admin'
      preLoaderRoute: typeof CabinetAdminRouteImport
      parentRoute: typeof CabinetRoute
    }
    '/cabinet/news/$slug': {
      id: '/cabinet/news/$slug'
      path: '/$slug'
      fullPath: '/cabinet/news/$slug'
      preLoaderRoute: typeof CabinetNewsSlugRouteImport
      parentRoute: typeof CabinetNewsRoute
    }
    '/cabinet/bank/transfer': {
      id: '/cabinet/bank/transfer'
      path: '/transfer'
      fullPath: '/cabinet/bank/transfer'
      preLoaderRoute: typeof CabinetBankTransferRouteImport
      parentRoute: typeof CabinetBankRoute
    }
    '/cabinet/bank/history': {
      id: '/cabinet/bank/history'
      path: '/history'
      fullPath: '/cabinet/bank/history'
      preLoaderRoute: typeof CabinetBankHistoryRouteImport
      parentRoute: typeof CabinetBankRoute
    }
    '/cabinet/bank/cards': {
      id: '/cabinet/bank/cards'
      path: '/cards'
      fullPath: '/cabinet/bank/cards'
      preLoaderRoute: typeof CabinetBankCardsRouteImport
      parentRoute: typeof CabinetBankRoute
    }
    '/cabinet/admin/whitelist': {
      id: '/cabinet/admin/whitelist'
      path: '/whitelist'
      fullPath: '/cabinet/admin/whitelist'
      preLoaderRoute: typeof CabinetAdminWhitelistRouteImport
      parentRoute: typeof CabinetAdminRoute
    }
    '/cabinet/admin/users': {
      id: '/cabinet/admin/users'
      path: '/users'
      fullPath: '/cabinet/admin/users'
      preLoaderRoute: typeof CabinetAdminUsersRouteImport
      parentRoute: typeof CabinetAdminRoute
    }
    '/cabinet/admin/promos': {
      id: '/cabinet/admin/promos'
      path: '/promos'
      fullPath: '/cabinet/admin/promos'
      preLoaderRoute: typeof CabinetAdminPromosRouteImport
      parentRoute: typeof CabinetAdminRoute
    }
    '/cabinet/admin/posts': {
      id: '/cabinet/admin/posts'
      path: '/posts'
      fullPath: '/cabinet/admin/posts'
      preLoaderRoute: typeof CabinetAdminPostsRouteImport
      parentRoute: typeof CabinetAdminRoute
    }
    '/cabinet/admin/payments': {
      id: '/cabinet/admin/payments'
      path: '/payments'
      fullPath: '/cabinet/admin/payments'
      preLoaderRoute: typeof CabinetAdminPaymentsRouteImport
      parentRoute: typeof CabinetAdminRoute
    }
    '/cabinet/admin/overview': {
      id: '/cabinet/admin/overview'
      path: '/overview'
      fullPath: '/cabinet/admin/overview'
      preLoaderRoute: typeof CabinetAdminOverviewRouteImport
      parentRoute: typeof CabinetAdminRoute
    }
    '/cabinet/admin/navigation': {
      id: '/cabinet/admin/navigation'
      path: '/navigation'
      fullPath: '/cabinet/admin/navigation'
      preLoaderRoute: typeof CabinetAdminNavigationRouteImport
      parentRoute: typeof CabinetAdminRoute
    }
    '/cabinet/admin/applications': {
      id: '/cabinet/admin/applications'
      path: '/applications'
      fullPath: '/cabinet/admin/applications'
      preLoaderRoute: typeof CabinetAdminApplicationsRouteImport
      parentRoute: typeof CabinetAdminRoute
    }
  }
}

interface CabinetAdminRouteChildren {
  CabinetAdminApplicationsRoute: typeof CabinetAdminApplicationsRoute
  CabinetAdminNavigationRoute: typeof CabinetAdminNavigationRoute
  CabinetAdminOverviewRoute: typeof CabinetAdminOverviewRoute
  CabinetAdminPaymentsRoute: typeof CabinetAdminPaymentsRoute
  CabinetAdminPostsRoute: typeof CabinetAdminPostsRoute
  CabinetAdminPromosRoute: typeof CabinetAdminPromosRoute
  CabinetAdminUsersRoute: typeof CabinetAdminUsersRoute
  CabinetAdminWhitelistRoute: typeof CabinetAdminWhitelistRoute
}

const CabinetAdminRouteChildren: CabinetAdminRouteChildren = {
  CabinetAdminApplicationsRoute: CabinetAdminApplicationsRoute,
  CabinetAdminNavigationRoute: CabinetAdminNavigationRoute,
  CabinetAdminOverviewRoute: CabinetAdminOverviewRoute,
  CabinetAdminPaymentsRoute: CabinetAdminPaymentsRoute,
  CabinetAdminPostsRoute: CabinetAdminPostsRoute,
  CabinetAdminPromosRoute: CabinetAdminPromosRoute,
  CabinetAdminUsersRoute: CabinetAdminUsersRoute,
  CabinetAdminWhitelistRoute: CabinetAdminWhitelistRoute,
}

const CabinetAdminRouteWithChildren = CabinetAdminRoute._addFileChildren(
  CabinetAdminRouteChildren,
)

interface CabinetBankRouteChildren {
  CabinetBankCardsRoute: typeof CabinetBankCardsRoute
  CabinetBankHistoryRoute: typeof CabinetBankHistoryRoute
  CabinetBankTransferRoute: typeof CabinetBankTransferRoute
}

const CabinetBankRouteChildren: CabinetBankRouteChildren = {
  CabinetBankCardsRoute: CabinetBankCardsRoute,
  CabinetBankHistoryRoute: CabinetBankHistoryRoute,
  CabinetBankTransferRoute: CabinetBankTransferRoute,
}

const CabinetBankRouteWithChildren = CabinetBankRoute._addFileChildren(
  CabinetBankRouteChildren,
)

interface CabinetNewsRouteChildren {
  CabinetNewsSlugRoute: typeof CabinetNewsSlugRoute
}

const CabinetNewsRouteChildren: CabinetNewsRouteChildren = {
  CabinetNewsSlugRoute: CabinetNewsSlugRoute,
}

const CabinetNewsRouteWithChildren = CabinetNewsRoute._addFileChildren(
  CabinetNewsRouteChildren,
)

interface CabinetRouteChildren {
  CabinetAdminRoute: typeof CabinetAdminRouteWithChildren
  CabinetBankRoute: typeof CabinetBankRouteWithChildren
  CabinetNewsRoute: typeof CabinetNewsRouteWithChildren
  CabinetStatsRoute: typeof CabinetStatsRoute
}

const CabinetRouteChildren: CabinetRouteChildren = {
  CabinetAdminRoute: CabinetAdminRouteWithChildren,
  CabinetBankRoute: CabinetBankRouteWithChildren,
  CabinetNewsRoute: CabinetNewsRouteWithChildren,
  CabinetStatsRoute: CabinetStatsRoute,
}

const CabinetRouteWithChildren =
  CabinetRoute._addFileChildren(CabinetRouteChildren)

interface NewsRouteChildren {
  NewsSlugRoute: typeof NewsSlugRoute
}

const NewsRouteChildren: NewsRouteChildren = {
  NewsSlugRoute: NewsSlugRoute,
}

const NewsRouteWithChildren = NewsRoute._addFileChildren(NewsRouteChildren)

interface PaymentRouteChildren {
  PaymentFailedRoute: typeof PaymentFailedRoute
  PaymentPendingRoute: typeof PaymentPendingRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
}

const PaymentRouteChildren: PaymentRouteChildren = {
  PaymentFailedRoute: PaymentFailedRoute,
  PaymentPendingRoute: PaymentPendingRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
}

const PaymentRouteWithChildren =
  PaymentRoute._addFileChildren(PaymentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  CabinetRoute: CabinetRouteWithChildren,
  JoinRoute: JoinRoute,
  LoginRoute: LoginRoute,
  MineRoute: MineRoute,
  NewsRoute: NewsRouteWithChildren,
  OfferRoute: OfferRoute,
  PaymentRoute: PaymentRouteWithChildren,
  PersonalDataConsentRoute: PersonalDataConsentRoute,
  PrivacyRoute: PrivacyRoute,
  RulesRoute: RulesRoute,
  StatsRoute: StatsRoute,
  UNicknameRoute: UNicknameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
