/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PlayersRouteImport } from './routes/players'
import { Route as PersonalDataConsentRouteImport } from './routes/personal-data-consent'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as OfferRouteImport } from './routes/offer'
import { Route as MineRouteImport } from './routes/mine'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CabinetRouteImport } from './routes/cabinet'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UNicknameRouteImport } from './routes/u.$nickname'
import { Route as PaymentSuccessRouteImport } from './routes/payment.success'
import { Route as PaymentPendingRouteImport } from './routes/payment.pending'
import { Route as PaymentFailedRouteImport } from './routes/payment.failed'
import { Route as CabinetBankRouteImport } from './routes/cabinet.bank'
import { Route as CabinetBankTransferRouteImport } from './routes/cabinet.bank.transfer'
import { Route as CabinetBankHistoryRouteImport } from './routes/cabinet.bank.history'
import { Route as CabinetBankCardsRouteImport } from './routes/cabinet.bank.cards'

const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersRoute = PlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalDataConsentRoute = PersonalDataConsentRouteImport.update({
  id: '/personal-data-consent',
  path: '/personal-data-consent',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const OfferRoute = OfferRouteImport.update({
  id: '/offer',
  path: '/offer',
  getParentRoute: () => rootRouteImport,
} as any)
const MineRoute = MineRouteImport.update({
  id: '/mine',
  path: '/mine',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CabinetRoute = CabinetRouteImport.update({
  id: '/cabinet',
  path: '/cabinet',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UNicknameRoute = UNicknameRouteImport.update({
  id: '/u/$nickname',
  path: '/u/$nickname',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => PaymentRoute,
} as any)
const PaymentPendingRoute = PaymentPendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => PaymentRoute,
} as any)
const PaymentFailedRoute = PaymentFailedRouteImport.update({
  id: '/failed',
  path: '/failed',
  getParentRoute: () => PaymentRoute,
} as any)
const CabinetBankRoute = CabinetBankRouteImport.update({
  id: '/bank',
  path: '/bank',
  getParentRoute: () => CabinetRoute,
} as any)
const CabinetBankTransferRoute = CabinetBankTransferRouteImport.update({
  id: '/transfer',
  path: '/transfer',
  getParentRoute: () => CabinetBankRoute,
} as any)
const CabinetBankHistoryRoute = CabinetBankHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => CabinetBankRoute,
} as any)
const CabinetBankCardsRoute = CabinetBankCardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => CabinetBankRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/cabinet': typeof CabinetRouteWithChildren
  '/login': typeof LoginRoute
  '/mine': typeof MineRoute
  '/offer': typeof OfferRoute
  '/payment': typeof PaymentRouteWithChildren
  '/personal-data-consent': typeof PersonalDataConsentRoute
  '/players': typeof PlayersRoute
  '/privacy': typeof PrivacyRoute
  '/rules': typeof RulesRoute
  '/cabinet/bank': typeof CabinetBankRouteWithChildren
  '/payment/failed': typeof PaymentFailedRoute
  '/payment/pending': typeof PaymentPendingRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/u/$nickname': typeof UNicknameRoute
  '/cabinet/bank/cards': typeof CabinetBankCardsRoute
  '/cabinet/bank/history': typeof CabinetBankHistoryRoute
  '/cabinet/bank/transfer': typeof CabinetBankTransferRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/cabinet': typeof CabinetRouteWithChildren
  '/login': typeof LoginRoute
  '/mine': typeof MineRoute
  '/offer': typeof OfferRoute
  '/payment': typeof PaymentRouteWithChildren
  '/personal-data-consent': typeof PersonalDataConsentRoute
  '/players': typeof PlayersRoute
  '/privacy': typeof PrivacyRoute
  '/rules': typeof RulesRoute
  '/cabinet/bank': typeof CabinetBankRouteWithChildren
  '/payment/failed': typeof PaymentFailedRoute
  '/payment/pending': typeof PaymentPendingRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/u/$nickname': typeof UNicknameRoute
  '/cabinet/bank/cards': typeof CabinetBankCardsRoute
  '/cabinet/bank/history': typeof CabinetBankHistoryRoute
  '/cabinet/bank/transfer': typeof CabinetBankTransferRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/cabinet': typeof CabinetRouteWithChildren
  '/login': typeof LoginRoute
  '/mine': typeof MineRoute
  '/offer': typeof OfferRoute
  '/payment': typeof PaymentRouteWithChildren
  '/personal-data-consent': typeof PersonalDataConsentRoute
  '/players': typeof PlayersRoute
  '/privacy': typeof PrivacyRoute
  '/rules': typeof RulesRoute
  '/cabinet/bank': typeof CabinetBankRouteWithChildren
  '/payment/failed': typeof PaymentFailedRoute
  '/payment/pending': typeof PaymentPendingRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/u/$nickname': typeof UNicknameRoute
  '/cabinet/bank/cards': typeof CabinetBankCardsRoute
  '/cabinet/bank/history': typeof CabinetBankHistoryRoute
  '/cabinet/bank/transfer': typeof CabinetBankTransferRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/cabinet'
    | '/login'
    | '/mine'
    | '/offer'
    | '/payment'
    | '/personal-data-consent'
    | '/players'
    | '/privacy'
    | '/rules'
    | '/cabinet/bank'
    | '/payment/failed'
    | '/payment/pending'
    | '/payment/success'
    | '/u/$nickname'
    | '/cabinet/bank/cards'
    | '/cabinet/bank/history'
    | '/cabinet/bank/transfer'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/cabinet'
    | '/login'
    | '/mine'
    | '/offer'
    | '/payment'
    | '/personal-data-consent'
    | '/players'
    | '/privacy'
    | '/rules'
    | '/cabinet/bank'
    | '/payment/failed'
    | '/payment/pending'
    | '/payment/success'
    | '/u/$nickname'
    | '/cabinet/bank/cards'
    | '/cabinet/bank/history'
    | '/cabinet/bank/transfer'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/cabinet'
    | '/login'
    | '/mine'
    | '/offer'
    | '/payment'
    | '/personal-data-consent'
    | '/players'
    | '/privacy'
    | '/rules'
    | '/cabinet/bank'
    | '/payment/failed'
    | '/payment/pending'
    | '/payment/success'
    | '/u/$nickname'
    | '/cabinet/bank/cards'
    | '/cabinet/bank/history'
    | '/cabinet/bank/transfer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  CabinetRoute: typeof CabinetRouteWithChildren
  LoginRoute: typeof LoginRoute
  MineRoute: typeof MineRoute
  OfferRoute: typeof OfferRoute
  PaymentRoute: typeof PaymentRouteWithChildren
  PersonalDataConsentRoute: typeof PersonalDataConsentRoute
  PlayersRoute: typeof PlayersRoute
  PrivacyRoute: typeof PrivacyRoute
  RulesRoute: typeof RulesRoute
  UNicknameRoute: typeof UNicknameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players': {
      id: '/players'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof PlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personal-data-consent': {
      id: '/personal-data-consent'
      path: '/personal-data-consent'
      fullPath: '/personal-data-consent'
      preLoaderRoute: typeof PersonalDataConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offer': {
      id: '/offer'
      path: '/offer'
      fullPath: '/offer'
      preLoaderRoute: typeof OfferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mine': {
      id: '/mine'
      path: '/mine'
      fullPath: '/mine'
      preLoaderRoute: typeof MineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cabinet': {
      id: '/cabinet'
      path: '/cabinet'
      fullPath: '/cabinet'
      preLoaderRoute: typeof CabinetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$nickname': {
      id: '/u/$nickname'
      path: '/u/$nickname'
      fullPath: '/u/$nickname'
      preLoaderRoute: typeof UNicknameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/success': {
      id: '/payment/success'
      path: '/success'
      fullPath: '/payment/success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof PaymentRoute
    }
    '/payment/pending': {
      id: '/payment/pending'
      path: '/pending'
      fullPath: '/payment/pending'
      preLoaderRoute: typeof PaymentPendingRouteImport
      parentRoute: typeof PaymentRoute
    }
    '/payment/failed': {
      id: '/payment/failed'
      path: '/failed'
      fullPath: '/payment/failed'
      preLoaderRoute: typeof PaymentFailedRouteImport
      parentRoute: typeof PaymentRoute
    }
    '/cabinet/bank': {
      id: '/cabinet/bank'
      path: '/bank'
      fullPath: '/cabinet/bank'
      preLoaderRoute: typeof CabinetBankRouteImport
      parentRoute: typeof CabinetRoute
    }
    '/cabinet/bank/transfer': {
      id: '/cabinet/bank/transfer'
      path: '/transfer'
      fullPath: '/cabinet/bank/transfer'
      preLoaderRoute: typeof CabinetBankTransferRouteImport
      parentRoute: typeof CabinetBankRoute
    }
    '/cabinet/bank/history': {
      id: '/cabinet/bank/history'
      path: '/history'
      fullPath: '/cabinet/bank/history'
      preLoaderRoute: typeof CabinetBankHistoryRouteImport
      parentRoute: typeof CabinetBankRoute
    }
    '/cabinet/bank/cards': {
      id: '/cabinet/bank/cards'
      path: '/cards'
      fullPath: '/cabinet/bank/cards'
      preLoaderRoute: typeof CabinetBankCardsRouteImport
      parentRoute: typeof CabinetBankRoute
    }
  }
}

interface CabinetBankRouteChildren {
  CabinetBankCardsRoute: typeof CabinetBankCardsRoute
  CabinetBankHistoryRoute: typeof CabinetBankHistoryRoute
  CabinetBankTransferRoute: typeof CabinetBankTransferRoute
}

const CabinetBankRouteChildren: CabinetBankRouteChildren = {
  CabinetBankCardsRoute: CabinetBankCardsRoute,
  CabinetBankHistoryRoute: CabinetBankHistoryRoute,
  CabinetBankTransferRoute: CabinetBankTransferRoute,
}

const CabinetBankRouteWithChildren = CabinetBankRoute._addFileChildren(
  CabinetBankRouteChildren,
)

interface CabinetRouteChildren {
  CabinetBankRoute: typeof CabinetBankRouteWithChildren
}

const CabinetRouteChildren: CabinetRouteChildren = {
  CabinetBankRoute: CabinetBankRouteWithChildren,
}

const CabinetRouteWithChildren =
  CabinetRoute._addFileChildren(CabinetRouteChildren)

interface PaymentRouteChildren {
  PaymentFailedRoute: typeof PaymentFailedRoute
  PaymentPendingRoute: typeof PaymentPendingRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
}

const PaymentRouteChildren: PaymentRouteChildren = {
  PaymentFailedRoute: PaymentFailedRoute,
  PaymentPendingRoute: PaymentPendingRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
}

const PaymentRouteWithChildren =
  PaymentRoute._addFileChildren(PaymentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  CabinetRoute: CabinetRouteWithChildren,
  LoginRoute: LoginRoute,
  MineRoute: MineRoute,
  OfferRoute: OfferRoute,
  PaymentRoute: PaymentRouteWithChildren,
  PersonalDataConsentRoute: PersonalDataConsentRoute,
  PlayersRoute: PlayersRoute,
  PrivacyRoute: PrivacyRoute,
  RulesRoute: RulesRoute,
  UNicknameRoute: UNicknameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
